language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.1
    - android-26
    - extra-android-m2repository

before_script:
 - chmod +x gradlew


script: ./gradlew build
